package app.cablegram.phone

import java.util.UUID
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put

/**
 * The payload envelope consumed by the control plane and the TV player. The [id] is generated by
 * the phone so a retried send cannot create a second command.
 */
internal fun remoteCommandBody(
    command: String,
    targetDeviceId: String,
    videoId: String? = null,
    arguments: JsonObject = buildJsonObject {},
    id: String = UUID.randomUUID().toString(),
): JsonObject {
    require(targetDeviceId.isNotBlank()) { "A remote command must target a paired TV" }
    return buildJsonObject {
        put("id", id)
        put("command", command)
        put("target_device_id", targetDeviceId)
        put("payload", buildJsonObject {
            arguments.forEach { (key, value) -> put(key, value) }
            videoId?.let { put("videoId", it) }
        })
    }
}

sealed interface TargetResult {
    data class Target(val deviceId: String, val name: String) : TargetResult
    data class Failed(val message: String) : TargetResult
}

/**
 * Picks the TV a remote command goes to. A selected TV that the household no longer lists is a
 * failure: a command must never fall back to a different TV. Only with nothing selected does the
 * first household TV serve as the default. [household] is null when it could not be loaded.
 */
fun resolveTarget(selected: PairedTv?, household: List<MeDevice>?): TargetResult {
    val none = TargetResult.Failed("No TV is paired with this household. Pair a TV to use the remote.")
    fun MeDevice.label() = displayName?.takeIf(String::isNotBlank) ?: "TV"
    return when {
        household == null -> selected?.deviceId?.let { TargetResult.Target(it, selected.name) } ?: none
        selected != null -> household.firstOrNull { it.id == selected.deviceId }?.let { TargetResult.Target(it.id, selected.name) }
            ?: TargetResult.Failed("${selected.name} is no longer connected. Choose a TV in Settings.")
        else -> household.firstOrNull()?.let { TargetResult.Target(it.id, it.label()) } ?: none
    }
}

/** Plain-language text for a reason the TV (or the server's expiry) rejected a command. */
fun rejectionMessage(reason: String?, tvName: String): String = when (reason) {
    "profile_required" -> "Choose a profile on the TV first."
    "title_unavailable" -> "$tvName can't find that title."
    "screen_unavailable" -> "$tvName can't do that on its current screen."
    "expired" -> "$tvName didn't respond in time. Check the TV."
    "execution_interrupted" -> "$tvName was interrupted. Try again."
    else -> "$tvName couldn't do that."
}
