package app.cablegram.telegram

import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Job
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.sync.Mutex

// Shared by apps/android-phone and apps/android-tv (spec 004). Keep both copies identical.

/** What the user sees of the Telegram connection. */
sealed interface TelegramState {
    data object Starting : TelegramState
    /** Phone: enter the phone number. */
    data object NeedsPhoneNumber : TelegramState
    data object NeedsCode : TelegramState
    data class NeedsPassword(val hint: String) : TelegramState
    /** TV: waiting for the household phone (or a QR scan) to approve [link]. */
    data class WaitingForApproval(val link: String) : TelegramState
    data class Ready(val user: TgUser) : TelegramState
    data object SignedOut : TelegramState
    data class Failed(val message: String) : TelegramState
}

/** What an approved login signed in; [session] is null when Telegram hadn't listed it within ~12 s. */
data class ApprovedLogin(val session: TgSessionInfo?)

/** Where the session runs: the phone logs in with number and code, a TV through QR / phone approval. */
enum class TelegramRole { Phone, Tv }

/**
 * One device's Telegram session (spec 004 US1, US2). Drives TDLib's authorization states, accepts one
 * user input at a time (a second tap while a request is in flight caused "Another authorization query
 * has started" in the spike), and exposes the result as [state].
 */
class TelegramSession(
    /** The Telegram layer this session signs in with; the library sync and file reader use it too. */
    val api: TelegramApi,
    private val role: TelegramRole,
    private val parameters: suspend () -> TgParameters,
    private val scope: CoroutineScope,
) {
    private val _state = MutableStateFlow<TelegramState>(TelegramState.Starting)
    val state: StateFlow<TelegramState> = _state.asStateFlow()

    private val _busy = MutableStateFlow(false)
    /** True while a phone number, code or password is being checked. */
    val busy: StateFlow<Boolean> = _busy.asStateFlow()

    private val _lastError = MutableStateFlow<String?>(null)
    /** Why the last phone number, code or password was rejected; cleared when Telegram moves on. */
    val lastError: StateFlow<String?> = _lastError.asStateFlow()

    /** Identity actually used to start this session, also used to verify newly approved devices. */
    @Volatile var clientApiId: Int = 0
        private set
    @Volatile private var startupUnavailable = false
    private val startupLock = Mutex()

    /** Retry configuration without recreating TDLib or deleting an existing account database. */
    fun retryStartup() {
        if (!startupUnavailable || !startupLock.tryLock()) return
        startupUnavailable = false
        _state.value = TelegramState.Starting
        scope.launch {
            try { handle(TgAuthState.WaitParameters) } finally { startupLock.unlock() }
        }
    }

    private val inputLock = Mutex()
    private var job: Job? = null

    fun start() {
        if (job != null) return
        job = scope.launch { api.authStates.collect { handle(it) } }
    }

    fun submitPhoneNumber(phone: String) = submit { api.setPhoneNumber(normalizePhone(phone)) }
    fun submitCode(code: String) = submit { api.checkCode(code.filter(Char::isDigit)) }
    fun submitPassword(password: String) = submit { api.checkPassword(password) }

    fun logOut() {
        scope.launch { runCatching { api.logOut() } }
    }

    /** Phone only: sign a TV in to this account from its login link, as Telegram's "Scan QR" does. */
    suspend fun approveTvLogin(link: String, ownApiId: Int): Result<ApprovedLogin> {
        check(role == TelegramRole.Phone) { "only the phone approves TV logins" }
        return approveVerified(link, ownApiId)
    }

    /** TV only: signs the household phone in to this account from the phone's login link (FR-023), as the phone does for a TV. */
    suspend fun approvePhoneLogin(link: String, ownApiId: Int): Result<ApprovedLogin> {
        check(role == TelegramRole.Tv) { "only a TV approves phone logins" }
        return approveVerified(link, ownApiId)
    }

    /**
     * Approves a login link and checks what it signed in. A link carries no proof of which app made it, so
     * a link generated by another Telegram client (e.g. Telegram Desktop on someone else's laptop) would
     * get a full session on the owner's account. So:
     *  - the sessions are listed first; if that fails, nothing is approved;
     *  - the one new session must use Cablegram's API id ([ownApiId]); if the only new session is another
     *    app's, it is ended at once and the approval fails (`UNEXPECTED_CLIENT`);
     *  - the identified session is returned, so the phone can end exactly that one later (FR-018), never
     *    an unrelated session such as the owner's own desktop.
     */
    private suspend fun approveVerified(link: String, ownApiId: Int): Result<ApprovedLogin> {
        if (!LOGIN_LINK.matches(link)) return Result.failure(IllegalArgumentException("not a Telegram login link"))
        val before = try {
            api.activeSessions().map { it.id }.toSet()
        } catch (e: TgException) {
            return Result.failure(TgException(e.code, "SESSIONS_UNAVAILABLE"))
        }
        try {
            api.confirmQrLogin(link)
        } catch (e: TgException) {
            return Result.failure(e)
        }
        repeat(IDENTIFY_ATTEMPTS) { attempt ->
            val fresh = runCatching { api.activeSessions() }.getOrNull().orEmpty().filter { !it.isCurrent && it.id !in before }
            fresh.filter { it.apiId == ownApiId }.maxByOrNull { it.logInDate }?.let { return Result.success(ApprovedLogin(it)) }
            if (fresh.size == 1) {
                runCatching { api.terminateSession(fresh.single().id) }
                return Result.failure(TgException(403, "UNEXPECTED_CLIENT"))
            }
            if (attempt < IDENTIFY_ATTEMPTS - 1) delay(IDENTIFY_WAIT_MS)
        }
        // Approved, but Telegram hasn't listed the new session yet: it can't be ended remotely.
        return Result.success(ApprovedLogin(null))
    }

    /** Phone only: sign in with a QR login (approved by a Home TV) instead of a phone number and code (FR-023). */
    fun startQrLogin() {
        check(role == TelegramRole.Phone) { "a TV always starts with a QR login" }
        submit { api.requestQrLogin() }
    }

    /**
     * The household's library channel. Opened by id when the household link already has one
     * ([knownChatId]); otherwise found by title, or created when [allowCreate] (phone only, US1).
     * Only this channel is ever read (FR-005).
     *
     * With [logoPath], a channel Cablegram creates gets the Cablegram logo, and so does an existing
     * one without a photo; a photo the owner chose is never replaced. A failed photo upload doesn't
     * fail linking.
     */
    suspend fun openLibrary(knownChatId: Long?, allowCreate: Boolean, logoPath: String? = null): TgLibrary? {
        val existing = knownChatId?.let { api.chat(it) }?.takeIf { it.isMember }
            ?: api.findChatByTitle(LIBRARY_TITLE)?.let { api.chat(it) }?.takeIf { it.isMember }
        val library = when {
            existing != null -> TgLibrary(existing.id, created = false)
            allowCreate -> TgLibrary(api.createChannel(LIBRARY_TITLE, LIBRARY_DESCRIPTION), created = true)
            else -> return null
        }
        if (logoPath != null && (library.created || existing?.hasPhoto == false)) {
            runCatching { api.setChannelPhoto(library.chatId, logoPath) }
        }
        return library
    }

    /** False when the owner left the linked channel or it was deleted: its videos are out of reach. */
    suspend fun isLibraryAvailable(chatId: Long): Boolean = api.chat(chatId)?.isMember == true

    internal suspend fun handle(auth: TgAuthState) {
        _lastError.value = null
        try {
            when (auth) {
                TgAuthState.WaitParameters -> {
                    val supplied = parameters()
                    clientApiId = supplied.apiId
                    api.start(supplied)
                }
                TgAuthState.WaitPhoneNumber -> if (role == TelegramRole.Tv) {
                    _state.value = TelegramState.Starting
                    api.requestQrLogin()
                } else {
                    _state.value = TelegramState.NeedsPhoneNumber
                }
                TgAuthState.WaitCode -> _state.value = TelegramState.NeedsCode
                is TgAuthState.WaitPassword -> _state.value = TelegramState.NeedsPassword(auth.hint)
                is TgAuthState.WaitOtherDevice -> _state.value = TelegramState.WaitingForApproval(auth.link)
                TgAuthState.Ready -> _state.value = TelegramState.Ready(api.me())
                TgAuthState.LoggingOut, TgAuthState.Closed -> _state.value = TelegramState.SignedOut
                is TgAuthState.Unsupported -> _state.value = TelegramState.Failed(unsupportedMessage(auth.name))
            }
        } catch (e: TelegramClientUnavailable) {
            startupUnavailable = true
            _state.value = TelegramState.Failed(e.message!!)
        } catch (e: TgException) {
            _state.value = TelegramState.Failed(describe(e))
        }
    }

    private fun submit(request: suspend () -> Unit) {
        if (!inputLock.tryLock()) return
        _busy.value = true
        scope.launch {
            try {
                request()
            } catch (e: TgException) {
                // Stay on the same step so the user can correct it; the message says what went wrong.
                _lastError.value = describe(e)
            } finally {
                _busy.value = false
                inputLock.unlock()
            }
        }
    }

    companion object {
        private const val IDENTIFY_ATTEMPTS = 6
        private const val IDENTIFY_WAIT_MS = 2_000L
        const val LIBRARY_TITLE = "Cablegram library"
        const val LIBRARY_DESCRIPTION = "Videos you share here appear in Cablegram on your TV."
        val LOGIN_LINK = Regex("""^tg://login\?token=[A-Za-z0-9_=-]{16,512}$""")

        /** Keeps digits and a leading +; Telegram wants the number in international format. */
        fun normalizePhone(raw: String): String {
            val trimmed = raw.trim()
            val digits = trimmed.filter(Char::isDigit)
            return if (trimmed.startsWith("+") || trimmed.startsWith("00")) "+" + digits.removePrefix(if (trimmed.startsWith("00")) "00" else "") else digits
        }

        fun describe(e: TgException): String = when {
            e.retryAfterSeconds != null -> "Telegram asks to wait ${formatWait(e.retryAfterSeconds!!)} before trying again."
            e.name.contains("PHONE_NUMBER_INVALID") -> "That phone number isn't valid. Include the country code, e.g. +31."
            e.name.contains("PHONE_CODE_INVALID") -> "That code isn't right. Check the latest code in Telegram."
            e.name.contains("PHONE_CODE_EXPIRED") -> "That code expired. Request a new one."
            e.name.contains("PASSWORD_HASH_INVALID") -> "That password isn't right."
            e.name.contains("SESSION_TOO_FRESH") || e.name.contains("FRESH_RESET_AUTHORISATION_FORBIDDEN") ->
                "Telegram doesn't allow this from a session less than 24 hours old. Try again later."
            // TDLib cannot open its local database (damaged, or its key was lost): only a fresh sign-in helps.
            Regex("database|malformed|encryption key|wrong key", RegexOption.IGNORE_CASE).containsMatchIn(e.name) ->
                "Telegram's data on this device is damaged. Disconnect Telegram and connect it again."
            else -> "Telegram error: ${e.name}"
        }

        private fun formatWait(seconds: Int): String = when {
            seconds < 90 -> "$seconds seconds"
            seconds < 5400 -> "${(seconds + 59) / 60} minutes"
            else -> "${(seconds + 3599) / 3600} hours"
        }

        private fun unsupportedMessage(name: String): String = when (name) {
            "WaitRegistration" -> "This phone number has no Telegram account. Create one in the Telegram app first."
            "WaitEmailAddress", "WaitEmailCode" -> "Telegram asks for an email step. Finish signing in once in the Telegram app, then try again."
            "WaitPremiumPurchase" -> "Telegram requires Premium to sign in on a new device from this number."
            else -> "Telegram asked for a step Cablegram doesn't support ($name)."
        }
    }
}
